# k8s/monitoreo/prometheus/prometheus-values.yaml

server:
  service:
    type: ClusterIP
    annotations: {}
  ingress:
    enabled: false
  baseURL: /prometheus
  # Solución al error: habilitar la recarga de configuración vía HTTP
  extraFlags:
    - --web.enable-lifecycle
  
  persistentVolume:
    enabled: true
    storageClass: "standard"
    size: 8Gi

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "standard"
    size: 2Gi
