# k8s/monitoreo/prometheus/prometheus-values.yaml

server:
  service:
    type: ClusterIP
    annotations: {}
  # Deshabilitamos el Ingress, ya que Nginx actuará como proxy
  ingress:
    enabled: false
  # Aquí configuramos la ruta base para Prometheus
  # Esto le dice a Prometheus que su URL de acceso es /prometheus
  base_url: /prometheus

  # Usar extraFlags para habilitar la recarga de configuración vía HTTP
  extraFlags:
    - --web.enable-lifecycle
  
  # Deshabilitamos el volumen persistente para simplificar el laboratorio.
  # Esto resuelve problemas de permisos y garantiza el inicio.
  persistentVolume:
    enabled: false

# Deshabilitamos la persistencia en el alertmanager para simplificar.
alertmanager:
  persistentVolume:
    enabled: false