server:
  extraScrapeConfigs: |
    # Job genérico que monitorea cualquier Pod con las anotaciones correctas
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      # Filtra para mantener solo los pods que tienen la anotación prometheus.io/scrape=true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Usa el valor de la anotación prometheus.io/path para establecer la ruta de las métricas
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Reescribe la dirección para incluir el puerto de la anotación, permitiendo puertos dinámicos.
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: '([^:]+)(?::\d+)?;(\d+)'
        replacement: '$1:$2'
      # Copia las etiquetas del pod al target de Prometheus
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)