# k8s/monitoreo/prometheus/prometheus-values.yaml

server:
  service:
    type: ClusterIP
    annotations: {}
  # Deshabilitamos el Ingress, ya que Nginx actuará como proxy.
  ingress:
    enabled: false
  # Aquí configuramos la ruta base para Prometheus.
  baseURL: /prometheus
  
  # CORRECCIÓN: Se elimina la línea 'extraArgs' porque el chart ya habilita
  # la funcionalidad de lifecycle por defecto.
  
  # Deshabilitamos la persistencia para simplificar el laboratorio.
  persistentVolume:
    enabled: false

# Deshabilitamos la persistencia en el alertmanager para simplificar.
alertmanager:
  enabled: false
  persistentVolume:
    enabled: false