# k8s/monitoreo/grafana/grafana-values.yaml

service:
  # El Service de Grafana será de tipo ClusterIP
  type: ClusterIP
  annotations: {}
  # Deshabilitamos el Ingress, ya que Nginx actuará como proxy.
  ingress:
    enabled: false

# Configuramos la ruta base para Grafana
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/grafana/"
    serve_from_sub_path: true

# Deshabilitamos la persistencia para simplificar el despliegue.
persistence:
  enabled: false